Importing numpy library and aliasing it as np

In [2]:
import numpy as np

Creating a numpy array: 

In [37]:
my_first_array= np.array(["ants","snake","leopard","lion","cat","dog","zebra"])
print(my_first_array)

['ants' 'snake' 'leopard' 'lion' 'cat' 'dog' 'zebra']


Access elements in my_first_array:

In [38]:
# if i want to access my last element individually in my_first_array:
my_first_array[3]

# if i want to access all elements in my_first_array: 
my_first_array[:-1]

# accessing from 2nd to last element: 
my_first_array[1:4]

# accessing the elements step wise:
my_first_array[0::2]



array(['ants', 'leopard', 'cat', 'zebra'], dtype='<U7')

Detecting the type of array: 

In [46]:
my_first_array.dtype


dtype('<U7')

Creating Multi-Dimensional Arrays:


In [69]:
my_two_dim_arrays= np.array([[1,2,3],
                            [4,5,6] ])



checking the dimensions of my_two_dim_arrays:

In [73]:
print(my_two_dim_arrays.shape)
print(my_two_dim_arrays.size)

(2, 3)
6


Creating a three dimensional array: 

In [83]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])
B.shape

(2, 2, 3)

Indexing and slicing of matrices: 

In [85]:
# Square matrix
my_square_matrix = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])


In [92]:
# now in order to access full row or column or a specific element:

print(my_square_matrix[0])
print(my_square_matrix[1])
print(my_square_matrix[2])
print(my_square_matrix[1,1])
print(my_square_matrix[0:3])

[1 2 3]
[4 5 6]
[7 8 9]
5
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Statistics Functions: 

In [96]:
# creating an array:
my_unique_array= np.array([1,2,3,4])
# adding all values of an array:
print(my_unique_array.sum())
print(my_unique_array.mean())


10
2.5


NUMPY FUNCTIONS: 


In [134]:
#random function

#the first function random, with size 2 generate a 2 values function from 0-1 range 
my_array_1= np.random.random(size=2)
print(my_array_1)

#normal function

#the normal function with size 2 generate a 2 value function from 
my_array_2= np.random.normal(size=2)
print(my_array_2)

#in order to generate the array with 2 rows and 4 columns from range of 0-1 range
my_array_3= np.random.rand(2,4)
print(my_array_3)

#in order to generate the array with 3 rows, 3 columns with random values from 0 to 100
my_array_4= np.random.randint(100,size=(3,3))
print(my_array_4)


#range functions: 
#creating a one dimensional array with values from 0 to 10(excluding)
my_array_4= np.arange(100)
print(my_array_4)

#create a array starting from 0 with increment 0.1 until reaches 1 
my_array_5= np.arange(0,1,0.1)
print(my_array_5)


#reshape functions:
#create an array of 1 dimension from 0 to 10, then reshape it into 2 rows and 5 columns using reshape function()
my_array_6= np.arange(10).reshape(2,5)
print(my_array_6) 



#zeros,ones,empty functions 
#generate 1D array with 5 zeros 
my_array_7= np.zeros(5)
print(my_array_7)

#generate 2D array with 3 rows and 3 columns:
my_array_8= np.zeros((3,3))
print(my_array_8)

#generate 2D array with 3 rows and 3 columns:
my_array_9= np.ones((3,3))
print(my_array_9)

[0.12367445 0.59032596]
[-1.10997739  1.82520862]
[[0.8988743  0.8236932  0.07403819 0.06584962]
 [0.67124804 0.80984554 0.94613012 0.29268694]]
[[53 72 74]
 [32 42 93]
 [62 35 71]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
